---

- name: Prepare operator resources
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:
  - name: Create Custom Resource Definition
    k8s:
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/osb_v1_templateservicebroker_crd.yaml'])) }}"

  - name: Ensure specified namespace is present
    k8s:
      api_version: v1
      kind: Namespace
      name: '{{ namespace }}'

  - name: Create RBAC resources
    k8s:
      definition: "{{ lookup('template', '/'.join([deploy_dir, 'testing', item])) }}"
      namespace: '{{ namespace }}'
    with_items:
      - role.yaml.j2
      - role_binding.yaml.j2
      - service_account.yaml.j2

  - name: Create ServiceCatalog ApiServer and ControllerManager
    k8s:
      definition:
        apiVersion: operator.openshift.io/v1
        kind: '{{ item }}'
        metadata:
          name: cluster
        spec:
          logLevel: Normal
          managementState: Managed
    with_items:
    - ServiceCatalogAPIServer
    - ServiceCatalogControllerManager

  - name: Wait a couple of seconds because of initial conditions on service catalog
    pause:
      seconds: 10

  - name: Wait 5m for Service Catalog Controller Manager to be complete
    k8s_facts:
      api_version: "operator.openshift.io/v1"
      kind: "ServiceCatalogControllerManager"
      name: "cluster"
    register: svccat_cm
    until:
    - "[ \"True\" ] in (svccat_cm | json_query('resources[].status.conditions[?type==`Available`].status'))"
    delay: 10
    retries: 30
